name: Infrastructure Pipeline

on:
  push:
    branches:
      - master
      - production
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'
  pull_request:
    branches:
      - master
      - production
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'

defaults:
  run:
    working-directory: ./infrastructure
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip
          unzip terraform_0.13.1_linux_amd64.zip
          sudo mv terraform /usr/local/bin

      - name: Terraform init
        run: terraform init -backend-config=stage.config

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file=stage.tfvars -out stage.plan

      - name: Terraform apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply stage.plan

      - if: ${{ always() }}
        run: rm stage.plan || true

  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip
          unzip terraform_0.13.1_linux_amd64.zip
          sudo mv terraform /usr/local/bin

      - name: Terraform init
        run: terraform init -backend-config=prod.config -input=false

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -var-file=prod.tfvars -out prod.plan

      - name: Terraform apply
        if: github.ref == 'refs/heads/production'
        run: terraform apply prod.plan

      - if: ${{ always() }}
        run: rm prod.plan || true